# -*- coding: utf-8 -*-
"""Samontan_ OpenAI Generate Image from Text Prompt combine with generate image variation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13R8ZmaecbyPYGSf2fo_cmElj01QB3Ikk
"""

!pip install openai

"""##### Environment variable for the hidden openAI API Key"""

# Commented out IPython magic to ensure Python compatibility.
# %env OPENAI_API_KEY=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

"""##### import the relevant libraries"""

import openai
import os
import matplotlib.pyplot as plt
import numpy as np
import urllib.request
from PIL import Image


openai.api_key = os.getenv("OPENAI_API_KEY")
def generate_image(input_string): 
  response = openai.Image.create(
    prompt=input_string,
    n=1,
    size="512x512"
  )
  image_url = response['data'][0]['url']
  return image_url

input_string = "a girl walking her dog in a field full of flowers"
output = generate_image(input_string)
print(f"Input: {input_string}\nOutput: {output}")

urllib.request.urlretrieve(output, 'output.png')
img = Image.open('output.png')
img_array = np.array(img)

plt.figure(figsize=(9,9))
ax = plt.axes(xticks=[], yticks=[])
ax.imshow(img_array)

"""#### Generate Image Variation #####"""

import openai
import os
import matplotlib.pyplot as plt
import numpy as np
import urllib.request
from PIL import Image

openai.api_key = os.getenv("OPENAI_API_KEY")
def image_variation(image_file): 
  response = openai.Image.create_variation(
  image=open(image_file, "rb"),
  n=1,
  size="512x512",
  )
  image_url = response['data'][0]['url']
  return image_url

#load the image
image_file = '/content/drive/MyDrive/Colab Notebooks/CCS229/colab data/data image.png'
img = Image.open(image_file)

img_array = np.array(img)
plt.figure(figsize=(9,9))
ax = plt.axes(xticks=[], yticks=[])
ax.set_title("Original Image")
ax.imshow(img_array)

from google.colab import drive
drive.mount('/content/drive')

#generate the image variation

output = image_variation(image_file)
print(f"Output file URL: {output}")

urllib.request.urlretrieve(output, 'output.png')
plt.figure(figsize=(9,9))
img = Image.open('output.png')
img_array = np.array(img)

ax.set_title("Variation Image")
ax = plt.axes(xticks=[], yticks=[])
ax.imshow(img_array)